CREATE TABLE despacho (
    numero INT PRIMARY KEY,
    despacho VARCHAR(100),
	documento INT,
	tipo int
);

CREATE TABLE tipo_despacho (
    nr INT PRIMARY KEY,
    nome VARCHAR(40)
);

INSERT INTO TIPO_DESPACHO VALUES ( 1, 'ARQUIVAMEHNTO');
INSERT INTO TIPO_DESPACHO VALUES ( 2, 'DESARQUIVAMENTO');
INSERT INTO TIPO_DESPACHO VALUES ( 3, 'REJETIÇÃO');
INSERT INTO TIPO_DESPACHO VALUES ( 4, 'APROVAÇÃO');
INSERT INTO TIPO_DESPACHO VALUES ( 5, 'ENCAMINHAMEHTO');
INSERT INTO TIPO_DESPACHO VALUES ( 6, 'NOTIFICAÇÃO');
INSERT INTO TIPO_DESPACHO VALUES ( 7, 'ADIAMEHTO');
INSERT INTO TIPO_DESPACHO VALUES ( 8, 'SOLICITAÇÃO DE INFORMAÇÕES');
INSERT INTO TIPO_DESPACHO VALUES ( 9, 'INTIMIÇÃO');
INSERT INTO TIPO_DESPACHO VALUES ( 10, 'EXPEDIÇÃO');
INSERT INTO TIPO_DESPACHO VALUES ( 11, 'AUTLRIZAÇÃO');

DO $$
DECLARE
    i INTEGER := 2;
    documento_id INTEGER;
BEGIN
INSERT INTO DESPACHO VALUES (1,'DESPACHO DOCUMENTO 50000', 50000, 1);
    WHILE i <= 15000000 LOOP
        documento_id := (random() * 49998)::INTEGER + 1;
        INSERT INTO DESPACHO (numero, despacho, documento, tipo)
        VALUES (i, 'DESPACHO DOCUMENTO ' || documento_id, documento_id, (random() * 10::INTEGER + 1));
        i := i + 1;
    END LOOP;
END $$;

ALTER TABLE despacho
ADD FOREIGN KEY (documento) REFERENCES documento(numero);

ALTER TABLE despacho
ADD FOREIGN KEY (tipo) REFERENCES tipo_despacho(nr);

